In [ ]:
import pandas as pd
import numpy as np

In [37]:
data=pd.read_csv("Creditcard_data.csv")

In [38]:
data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,1
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [39]:
y=data["Class"]

In [40]:
x=data[data.columns.drop("Class")]

In [41]:
x.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,0.251412,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.069083,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.524980,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.208038,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,0.408542,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99

In [42]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Class, dtype: int64

In [8]:
!pip install imblearn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imblearn in c:\users\91982\appdata\roaming\python\python311\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\91982\appdata\roaming\python\python311\site-packages (from imblearn) (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\91982\appdata\roaming\python\python311\site-packages (from imbalanced-learn->imblearn) (1.24.1)
Requirement already satisfied: scipy>=1.3.2 in c:\users\91982\appdata\roaming\python\python311\site-packages (from imbalanced-learn->imblearn) (1.10.0)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\91982\appdata\roaming\python\python311\site-packages (from imbalanced-learn->imblearn) (1.2.0)
Requirement already satisfied: joblib>=1.1.1 in c:\users\91982\appdata\roaming\python\python311\site-packages (from imbalanced-learn->imblearn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\91982\appdata\roaming\python\python311\site-packages (from imbalanced-learn->imblearn) (3.1.0)

In [9]:
from imblearn.under_sampling import TomekLinks
from imblearn.over_sampling import RandomOverSampler

In [43]:
tl = RandomOverSampler(random_state=42)
# ros = RandomOverSampler()
# fit predictor and target variable
x_tl, y_tl = tl.fit_resample(x, y)

print('Original dataset shape', y.value_counts())
print('Resample dataset shape', y_tl.value_counts())

Original dataset shape 0    763
1      9
Name: Class, dtype: int64
Resample dataset shape 0    763
1    763
Name: Class, dtype: int64

In [44]:
#Random Sampling
import random

In [45]:
x_s1=x_tl.sample(100,random_state=24)
y_s1=y_tl.sample(100,random_state=24)

In [46]:
#Systematic Sampling
import math

In [47]:
# Define the sampling interval
interval = math.floor(x_tl.shape[0]/100)
# Determine the starting point
start = 5
# Perform systematic sampling
x_s2 = x_tl.iloc[start::interval]
y_s2 = y_tl.iloc[start::interval]
# View the sampled data
print(x_s2,y_s2)

      Time        V1        V2        V3        V4        V5        V6  \
5        2 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728
20      16  0.694885 -1.361819  1.029221  0.834159 -1.191209  1.309109
35      26 -0.535388  0.865268  1.351076  0.147575  0.433680  0.086983
50      35  1.199356  0.129953  0.863585  1.002635 -0.783761 -0.884679
65      44 -0.899992  0.136255  1.883665 -0.208996  1.051441  1.905241
...    ...       ...       ...       ...       ...       ...       ...
1460   539 -1.738582  0.052740  1.187057 -0.656652  0.920623 -0.291788
1475   484 -0.928088  0.398194  1.741131  0.182673  0.966387 -0.901004
1490   406 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545
1505   118  1.254914  0.350287  0.302488  0.693114 -0.371470 -1.070256
1520   574  1.257719  0.364739  0.306923  0.690638 -0.357792 -1.067481

            V7        V8        V9  ...       V20       V21       V22  \
5     0.476201  0.260314 -0.568671  ...  0.084968 -0.208254 -0.559825
20   -0.878586  0.445290 -0.446196  ... -0.138334 -0.295583 -0.571955
35    0.693039  0.179742 -0.285642  ... -0.283264  0.049526  0.206537
50   -0.040743 -0.208069  0.392478  ... -0.072620 -0.042468  0.198474
65    0.241423  0.647631 -0.053466  ... -0.121726 -0.081500 -0.016926
...        ...       ...       ...  ...       ...       ...       ...
1460  0.269083  0.140631  0.023464  ...  0.002974 -0.179545 -0.192036
1475  0.879016 -0.156590 -0.142117  ... -0.118283  0.066353  0.281378
1490 -2.537387  1.391657 -2.770089  ...  0.126911  0.517232 -0.035049
1505  0.086781 -0.202836  0.035154  ... -0.079756 -0.287592 -0.832682
1520  0.094272 -0.210300  0.014455  ... -0.073779 -0.286856 -0.820658

           V23       V24       V25       V26       V27       V28  Amount
5    -0.026398 -0.371427 -0.232794  0.105915  0.253844  0.081080    3.67
20   -0.050881 -0.304215  0.072001 -0.422234  0.086553  0.063499  231.71
35   -0.187108  0.000753  0.098117 -0.553471 -0.078306  0.025427    1.77
50   -0.033010  1.013290  0.559098  0.401818 -0.005865  0.017936    0.99
65   -0.147706 -1.384620 -0.024352  0.412659 -0.106776 -0.190476   21.55
...        ...       ...       ...       ...       ...       ...     ...
1460 -0.261879 -0.237477 -0.335040  0.240323 -0.345129 -0.383563    1.00
1475 -0.257966  0.385384  0.391117 -0.453853 -0.104448 -0.125765    1.00
1490 -0.465211  0.320198  0.044519  0.177840  0.261145 -0.143276    0.00
1505  0.128083  0.339427  0.215944  0.094704 -0.023354  0.030892    2.69
1520  0.127663  0.343128  0.221120  0.094391 -0.022189  0.030944    1.29

[102 rows x 30 columns] 5       0
20      0
35      0
50      0
65      0
       ..
1460    1
1475    1
1490    1
1505    1
1520    1
Name: Class, Length: 102, dtype: int64

In [48]:
#Stratified Sampling

In [49]:
x_s3_0=x_tl[y_tl.iloc[:]==0]
x_s3_1=x_tl[y_tl.iloc[:]==1]
y_s3_0=y_tl[y_tl.iloc[:]==0]
y_s3_1=y_tl[y_tl.iloc[:]==1]

In [50]:
print(x_s3_0,y_s3_0)

     Time        V1        V2        V3        V4        V5        V6  \
0       0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388
2       1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499
3       1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203
4       2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921
5       2 -0.425966  0.960523  1.141109 -0.168252  0.420987 -0.029728
..    ...       ...       ...       ...       ...       ...       ...
767   575 -0.572263  0.731748  1.541254  0.150506  1.108974  0.372152
768   579 -1.296845 -0.511605  2.404726 -0.310762 -0.319551 -0.542842
769   579  1.214170  0.210481  0.484651  0.479768 -0.261955 -0.527039
770   580  1.267030 -0.071114  0.037680  0.512683  0.242392  0.705212
771   581  1.153758  0.132273  0.382969  1.405063 -0.224287 -0.197295

           V7        V8        V9  ...       V20       V21       V22  \
0    0.239599  0.098698  0.363787  ...  0.251412 -0.018307  0.277838
2    0.791461  0.247676 -1.514654  ...  0.524980  0.247998  0.771679
3    0.237609  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274
4    0.592941 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278
5    0.476201  0.260314 -0.568671  ...  0.084968 -0.208254 -0.559825
..        ...       ...       ...  ...       ...       ...       ...
767  1.084879 -0.146329 -0.274447  ...  0.056544 -0.143508 -0.107582
768 -0.173310  0.260423 -1.202688  ... -0.349668 -0.071270 -0.161175
769  0.021782 -0.106888 -0.037631  ... -0.071540 -0.224292 -0.594609
770 -0.226582  0.109483  0.657565  ... -0.066990 -0.164468 -0.177225
771  0.020653  0.029260  0.412254  ... -0.230877 -0.107809 -0.125231

          V23       V24       V25       V26       V27       V28  Amount
0   -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62
2    0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66
3   -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50
4   -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99
5   -0.026398 -0.371427 -0.232794  0.105915  0.253844  0.081080    3.67
..        ...       ...       ...       ...       ...       ...     ...
767 -0.418263 -0.731029  0.877525 -0.364150 -0.177509 -0.256545   26.72
768  0.088496  0.285390  0.281069 -0.370130  0.043410  0.092318   80.00
769  0.159877  0.091873  0.140964  0.227406 -0.017389  0.016030    5.98
770 -0.222918 -1.245505  0.678360  0.525059  0.002920 -0.003333   12.36
771 -0.057041  0.073082  0.633977 -0.310685  0.033590  0.015250   13.79

[763 rows x 30 columns] 0      0
2      0
3      0
4      0
5      0
      ..
767    0
768    0
769    0
770    0
771    0
Name: Class, Length: 763, dtype: int64

In [51]:
x_s3=x_s3_0.sample(50,random_state=24)
x_s3=x_s3.append(x_s3_1.sample(50,random_state=24))
y_s3=y_s3_0.sample(50,random_state=24)
y_s3=y_s3.append(y_s3_1.sample(50,random_state=24))

C:\Users\91982\AppData\Local\Temp\ipykernel_5980\2747500316.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  x_s3=x_s3.append(x_s3_1.sample(50,random_state=24))
C:\Users\91982\AppData\Local\Temp\ipykernel_5980\2747500316.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  y_s3=y_s3.append(y_s3_1.sample(50,random_state=24))

In [52]:
y_s3.shape

(100,)